name: Deploy to Link-Host

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Prepare files for deployment
      run: |
        # Копируем статические файлы в dist
        cp -r css dist/
        cp -r favicon dist/
        cp -r images dist/
        cp script.js dist/
        
        # Показываем содержимое dist
        echo "Contents of dist folder:"
        ls -la dist/
        
    - name: Deploy to Link-Host
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Starting deployment..."
          
          # Создаем папку если её нет
          mkdir -p /www/welcome-to-day.ru/
          
          # Очищаем папку
          rm -rf /www/welcome-to-day.ru/*
          
          echo "Folder prepared for deployment"
        
    - name: Upload files
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "dist/*"
        target: "/www/welcome-to-day.ru/"
        strip_components: 1
        
    - name: Verify deployment
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          echo "Checking deployed files..."
          ls -la /www/welcome-to-day.ru/
          chmod -R 755 /www/welcome-to-day.ru/
          echo "Deployment completed successfully!" 